### ISSUE TITLE
Error when using filter 'overdue'

### ISSUE THREAD

**Issue by Semir1212** [humhub/tasks#212]
HH 1.12
Tasks 1.6.2

yii\base\ErrorException: in_array() expects parameter 2 to be array, string given in /srv/www/htdocs/doku2/modules/tasks/models/forms/TaskFilter.php:161
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /srv/www/htdocs/doku2/modules/tasks/models/forms/TaskFilter.php(161): in_array()
#2 /srv/www/htdocs/doku2/modules/tasks/models/forms/TaskFilter.php(104): humhub\modules\tasks\models\forms\TaskFilter->isFilterActive()
#3 /srv/www/htdocs/doku2/modules/tasks/widgets/search/TaskSearchList.php(40): humhub\modules\tasks\models\forms\TaskFilter->query()
#4 /srv/humhub/protected/humhub/components/Widget.php(63): humhub\modules\tasks\widgets\search\TaskSearchList->run()
#5 /srv/www/htdocs/doku2/modules/tasks/controllers/GlobalController.php(43): humhub\components\Widget::widget()
#6 [internal function]: humhub\modules\tasks\controllers\GlobalController->actionFilter()
#7 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#9 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#10 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#12 /srv/www/htdocs/doku2/index.php(24): yii\base\Application->run()
#13 {main}

In combination with other filters: 

TypeError: t.push is not a functionTypeError: t.push is not a function
    at https://doku2.humhub.com/static/js/humhub-bundle.js?v=1664297382:1:1233056
    at Array.forEach ()
    at d.getFilterMap (https://doku2.humhub.com/static/js/humhub-bundle.js?v=1664297382:1:1232974)
    at TaskFilter.buildRequestFilterData (:85:21)
    at TaskFilter.loadUpdate (:59:29)
    at Object. (:24:18)
    at Object.dispatch (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:42694)
    at f.handle (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:40691)
    at Object.trigger (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:71039)
    at Object. (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:71630)
    at Function.each (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:2981)
    at k.fn.init.each (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:1478)
    at k.fn.init.trigger (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:71606)
    at o.extendable.init.t.trigger (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:496757)
    at o.extendable.init.t.n [as trigger] (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:88204)
    at u.fire (https://doku2.humhub.com/static/js/humhub-app.js?v=1664297358:1:523700)

Can you please take a look into this @yurabakhtin

**Comment by luke-** [comment]
@yurabakhtin Thank you!
